### ISSUE TITLE
Merge conflicts in kgcl.owl.ttl 

### ISSUE THREAD

**Issue by nlharris** [INCATools/kgcl-rdflib#68]
https://github.com/INCATools/kgcl-rdflib/blob/master/owl/kgcl.owl.ttl has merge conflicts that need to be resolved (the first one starts at line 63).

**Comment by cmungall** [comment]
The action here is to remove *all* generated files in this repo, everything under owl/ and python/. These are now in the main repo!

**Comment by nlharris** [comment]
@cmungall @caufieldjh https://github.com/INCATools/kgcl-rdflib/blob/master/owl/kgcl.owl.ttl still exists and still has merge conflicts - should it be removed? Is there a PR for removing these generated files, as Chris suggested?

**Comment by caufieldjh** [comment]
Yes, those changes are now in https://github.com/INCATools/kgcl-rdflib/pull/69 - ready to merge (I can do it if given write access to this repo)

**Comment by nlharris** [comment]
#69 merged; closing this as fixed.
